model_name: cbow

dataset: Own
data_dir: data/
train_batch_size: 50
val_batch_size: 50
shuffle: True

optimizer: Adam
learning_rate: 0.01
epochs: 14
train_steps: 
val_steps: 

checkpoint_frequency: True 
model_dir: weights/cbow_own5
PathModel: weights/cbow_own4/model.pt
